#!/usr/bin/env bash
# Regenerate Go code from the .proto files. Run from any directory.
# Requires `protoc` and `protoc-gen-go` on PATH.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROTO_DIR="$(cd "$BACKEND_DIR/../proto" && pwd)"
OUT_DIR="$BACKEND_DIR/gen"

if ! command -v protoc >/dev/null; then
    echo "protoc not found on PATH" >&2
    exit 1
fi
if ! command -v protoc-gen-go >/dev/null; then
    echo "protoc-gen-go not found on PATH (try: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest)" >&2
    exit 1
fi

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

protoc \
    --proto_path="$PROTO_DIR" \
    --go_out="$OUT_DIR" \
    --go_opt=paths=source_relative \
    "$PROTO_DIR"/hilglebone/v1/*.proto

# Marker so anyone browsing the repo knows this directory is regenerated.
cat > "$OUT_DIR/_GENERATED.md" <<'MD'
# Generated code — do not edit by hand

The `hilglebone/v1/*.pb.go` files in this directory are generated by `protoc`
from the shared `.proto` definitions in the repo's top-level `proto/` folder.

To regenerate after changing a `.proto`:

```bash
./backend/scripts/gen-proto.sh
```

The Python equivalent lives at `bbb/hilglebone/v1/`, regenerated via
`./bbb/scripts/gen-proto.sh`. Both should be re-run together whenever a
shared proto file changes, so the cloud and BBB stay on the same wire format.

## Why this directory exists under `gen/` (and not directly under `backend/`)

`protoc-gen-go` puts all messages from one proto package into a single Go
package, with no inter-file imports — so the directory can sit anywhere the
Go module path allows. We park it under `backend/gen/` purely as a visual
marker that this is machine-generated output.

(Contrast with the Python side, where `protoc-gen-python` emits absolute
`from hilglebone.v1 import …` imports and forces the directory to sit at the
package root.)
MD

echo "Generated Go code in $OUT_DIR"
