#!/usr/bin/env bash
# Regenerate Python code from the shared .proto files. Run from anywhere.
# Requires `protoc` on PATH.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BBB_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROTO_DIR="$(cd "$BBB_DIR/../proto" && pwd)"
# Generated code lands at bbb/hilglebone/v1/ so the absolute imports protoc
# emits (`from hilglebone.v1 import …_pb2`) resolve via the editable install.
OUT_DIR="$BBB_DIR"
PKG_DIR="$OUT_DIR/hilglebone"

if ! command -v protoc >/dev/null; then
    echo "protoc not found on PATH" >&2
    exit 1
fi

rm -rf "$PKG_DIR"
mkdir -p "$PKG_DIR/v1"
touch "$PKG_DIR/__init__.py"
touch "$PKG_DIR/v1/__init__.py"

protoc \
    --proto_path="$PROTO_DIR" \
    --python_out="$OUT_DIR" \
    --pyi_out="$OUT_DIR" \
    "$PROTO_DIR"/hilglebone/v1/*.proto

# Marker so anyone browsing the repo knows this directory is regenerated.
cat > "$PKG_DIR/_GENERATED.md" <<'MD'
# Generated code — do not edit by hand

The `hilglebone/v1/*_pb2.py` and `*_pb2.pyi` files in this directory are
generated by `protoc` from the shared `.proto` definitions in the repo's
top-level `proto/` folder.

To regenerate after changing a `.proto`:

```bash
./bbb/scripts/gen-proto.sh
```

The Go equivalent lives at `backend/gen/hilglebone/v1/`, regenerated via
`./backend/scripts/gen-proto.sh`. Both should be re-run together whenever a
shared proto file changes, so the cloud and BBB stay on the same wire format.

## Why this directory sits at the top level of `bbb/`

Unlike the Go output (which is parked under `backend/gen/` as a visual marker),
the Python output has to live at this exact path. `protoc-gen-python` emits
absolute imports between generated files — e.g. `status_pb2.py` contains
`from hilglebone.v1 import common_pb2`. For those imports to resolve, the
`hilglebone` package must be importable as a top-level name, which means the
directory has to sit at the package root.
MD

echo "Generated Python proto code in $PKG_DIR"
