# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hilglebone/v1/command.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'hilglebone/v1/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hilglebone.v1 import common_pb2 as hilglebone_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bhilglebone/v1/command.proto\x12\rhilglebone.v1\x1a\x1ahilglebone/v1/common.proto\"T\n\x12SetupSensorCommand\x12.\n\x0bprotocol_id\x18\x01 \x01(\x0e\x32\x19.hilglebone.v1.ProtocolId\x12\x0e\n\x06\x63onfig\x18\x02 \x01(\x0c\"5\n\x10SetOutputCommand\x12\x11\n\tsensor_id\x18\x01 \x01(\r\x12\x0e\n\x06values\x18\x02 \x01(\x0c\"&\n\x11StopSensorCommand\x12\x11\n\tsensor_id\x18\x01 \x01(\r\"\"\n\x0fScenarioCommand\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"\r\n\x0bSyncCommand\"\x15\n\x13SessionStartCommand\"\x14\n\x12SessionStopCommand\"\xa6\x02\n\x0eRuntimeCommand\x12\x39\n\x0csetup_sensor\x18\x01 \x01(\x0b\x32!.hilglebone.v1.SetupSensorCommandH\x00\x12\x35\n\nset_output\x18\x02 \x01(\x0b\x32\x1f.hilglebone.v1.SetOutputCommandH\x00\x12\x37\n\x0bstop_sensor\x18\x03 \x01(\x0b\x32 .hilglebone.v1.StopSensorCommandH\x00\x12\x32\n\x08scenario\x18\x04 \x01(\x0b\x32\x1e.hilglebone.v1.ScenarioCommandH\x00\x12*\n\x04sync\x18\x05 \x01(\x0b\x32\x1a.hilglebone.v1.SyncCommandH\x00\x42\t\n\x07payload\"\x97\x02\n\x0f\x43ommandEnvelope\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x11\n\tdevice_id\x18\x03 \x01(\t\x12\x14\n\x0ctimestamp_us\x18\x04 \x01(\x03\x12;\n\rsession_start\x18\n \x01(\x0b\x32\".hilglebone.v1.SessionStartCommandH\x00\x12\x39\n\x0csession_stop\x18\x0b \x01(\x0b\x32!.hilglebone.v1.SessionStopCommandH\x00\x12\x30\n\x07runtime\x18\x0c \x01(\x0b\x32\x1d.hilglebone.v1.RuntimeCommandH\x00\x42\t\n\x07payloadB8Z6github.com/kibshh/HILglebone/backend/gen/hilglebone/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hilglebone.v1.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/kibshh/HILglebone/backend/gen/hilglebone/v1'
  _globals['_SETUPSENSORCOMMAND']._serialized_start=74
  _globals['_SETUPSENSORCOMMAND']._serialized_end=158
  _globals['_SETOUTPUTCOMMAND']._serialized_start=160
  _globals['_SETOUTPUTCOMMAND']._serialized_end=213
  _globals['_STOPSENSORCOMMAND']._serialized_start=215
  _globals['_STOPSENSORCOMMAND']._serialized_end=253
  _globals['_SCENARIOCOMMAND']._serialized_start=255
  _globals['_SCENARIOCOMMAND']._serialized_end=289
  _globals['_SYNCCOMMAND']._serialized_start=291
  _globals['_SYNCCOMMAND']._serialized_end=304
  _globals['_SESSIONSTARTCOMMAND']._serialized_start=306
  _globals['_SESSIONSTARTCOMMAND']._serialized_end=327
  _globals['_SESSIONSTOPCOMMAND']._serialized_start=329
  _globals['_SESSIONSTOPCOMMAND']._serialized_end=349
  _globals['_RUNTIMECOMMAND']._serialized_start=352
  _globals['_RUNTIMECOMMAND']._serialized_end=646
  _globals['_COMMANDENVELOPE']._serialized_start=649
  _globals['_COMMANDENVELOPE']._serialized_end=928
# @@protoc_insertion_point(module_scope)
