# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hilglebone/v1/common.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'hilglebone/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ahilglebone/v1/common.proto\x12\rhilglebone.v1*\xfa\x01\n\nProtocolId\x12\x1b\n\x17PROTOCOL_ID_UNSPECIFIED\x10\x00\x12\x13\n\x0fPROTOCOL_ID_I2C\x10\x01\x12\x13\n\x0fPROTOCOL_ID_SPI\x10\x02\x12\x1b\n\x17PROTOCOL_ID_DIGITAL_OUT\x10\x03\x12\x1a\n\x16PROTOCOL_ID_DIGITAL_IN\x10\x04\x12\x13\n\x0fPROTOCOL_ID_DAC\x10\x05\x12\x13\n\x0fPROTOCOL_ID_PWM\x10\x06\x12\x14\n\x10PROTOCOL_ID_FREQ\x10\x07\x12\x17\n\x13PROTOCOL_ID_ONEWIRE\x10\x08\x12\x13\n\x0fPROTOCOL_ID_CAN\x10\t*r\n\nStm32State\x12\x1b\n\x17STM32_STATE_UNSPECIFIED\x10\x00\x12\x16\n\x12STM32_STATE_SYNCED\x10\x01\x12\x18\n\x14STM32_STATE_UNSYNCED\x10\x02\x12\x15\n\x11STM32_STATE_ERROR\x10\x03\x42\x38Z6github.com/kibshh/HILglebone/backend/gen/hilglebone/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hilglebone.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/kibshh/HILglebone/backend/gen/hilglebone/v1'
  _globals['_PROTOCOLID']._serialized_start=46
  _globals['_PROTOCOLID']._serialized_end=296
  _globals['_STM32STATE']._serialized_start=298
  _globals['_STM32STATE']._serialized_end=412
# @@protoc_insertion_point(module_scope)
