# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hilglebone/v1/ota.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'hilglebone/v1/ota.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17hilglebone/v1/ota.proto\x12\rhilglebone.v1\"\xa4\x01\n\x0bOtaEnvelope\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x11\n\tdevice_id\x18\x03 \x01(\t\x12\x14\n\x0ctimestamp_us\x18\x04 \x01(\x03\x12\x14\n\x0c\x66irmware_url\x18\x05 \x01(\t\x12\x17\n\x0f\x66irmware_sha256\x18\x06 \x01(\t\x12\x15\n\rfirmware_size\x18\x07 \x01(\x04\x42\x38Z6github.com/kibshh/HILglebone/backend/gen/hilglebone/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hilglebone.v1.ota_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/kibshh/HILglebone/backend/gen/hilglebone/v1'
  _globals['_OTAENVELOPE']._serialized_start=43
  _globals['_OTAENVELOPE']._serialized_end=207
# @@protoc_insertion_point(module_scope)
