# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hilglebone/v1/status.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'hilglebone/v1/status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hilglebone.v1 import common_pb2 as hilglebone_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ahilglebone/v1/status.proto\x12\rhilglebone.v1\x1a\x1ahilglebone/v1/common.proto\"\xb1\x01\n\x0eStatusEnvelope\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x14\n\x0ctimestamp_us\x18\x03 \x01(\x03\x12\x32\n\ronline_status\x18\x04 \x01(\x0e\x32\x1b.hilglebone.v1.OnlineStatus\x12.\n\x0bstm32_state\x18\x05 \x01(\x0e\x32\x19.hilglebone.v1.Stm32State*z\n\x0cOnlineStatus\x12\x1d\n\x19ONLINE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n\x14ONLINE_STATUS_ONLINE\x10\x01\x12\x16\n\x12ONLINE_STATUS_BUSY\x10\x02\x12\x19\n\x15ONLINE_STATUS_OFFLINE\x10\x03\x42\x38Z6github.com/kibshh/HILglebone/backend/gen/hilglebone/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hilglebone.v1.status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/kibshh/HILglebone/backend/gen/hilglebone/v1'
  _globals['_ONLINESTATUS']._serialized_start=253
  _globals['_ONLINESTATUS']._serialized_end=375
  _globals['_STATUSENVELOPE']._serialized_start=74
  _globals['_STATUSENVELOPE']._serialized_end=251
# @@protoc_insertion_point(module_scope)
